# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly
    - os: osx
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
 # - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 # - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("Parquet"); Pkg.test("Parquet"; coverage=true)'
